# Generated by Django 4.2.15 on 2024-11-30 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactdetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "emailname",
                    models.EmailField(default="", max_length=254, unique=True),
                ),
                (
                    "phonenumber",
                    models.CharField(
                        default="",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phonenumber",
                                message="Phone number must only contain numeric values.",
                                regex="^[0-9]+$",
                            )
                        ],
                    ),
                ),
                ("message", models.TextField(default="")),
            ],
            options={
                "verbose_name_plural": "Contact detail",
            },
        ),
        migrations.CreateModel(
            name="RecipientEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emailaddress", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
