# Generated by Django 4.2.15 on 2024-12-10 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_homeproperties_realestateproperty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeproperties",
            options={"verbose_name_plural": "Home_property"},
        ),
        migrations.AlterModelOptions(
            name="realestateproperty",
            options={"verbose_name_plural": "Realstate_Property"},
        ),
        migrations.CreateModel(
            name="Kyc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("aadhar_card_number", models.CharField(max_length=12, unique=True)),
                ("pan_number", models.CharField(max_length=10, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kycs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_holder_name", models.CharField(max_length=100)),
                ("bank_account_number", models.CharField(max_length=20, unique=True)),
                ("ifsc_code", models.CharField(max_length=11)),
                ("branch_name", models.CharField(max_length=100)),
                (
                    "kyc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="app.kyc",
                    ),
                ),
            ],
        ),
    ]
