# Generated by Django 4.2.15 on 2024-12-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_homeproperties_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kyc",
            name="user",
        ),
        migrations.DeleteModel(
            name="BankDetails",
        ),
        migrations.DeleteModel(
            name="Kyc",
        ),
    ]
